test:
  image: yourlabs/python
  script:
  - pip install -e .
  - ./example.py middlewares | tee -a middlewares.out
  - grep TestMiddleware middlewares.out
  - ./example.py urls | tee -a urls.out
  - grep test_view middlewares.out

qa:
  stage: test
  image: yourlabs/python
  script: flake8

pypi:
  stage: deploy
  image: yourlabs/python
  script: pypi-release
  only:
    refs:
    - tags
